[build-system]
build-backend = "jupyter_packaging.build_api"
requires = ["jupyter_packaging~=0.10,<2", "jupyterlab>=4.0.0a25"]

[tool.jupyter-packaging.options]
ensured-targets = ["packages/jupytercad/labextension/static/style.js", "packages/jupytercad/labextension/package.json"]
skip-if-exists = ["packages/jupytercad/labextension/static/style.js"]

[tool.jupyter-packaging.builder]
factory = "jupyter_packaging.npm_builder"

[tool.jupyter-packaging.build-args]
build_cmd = "build:prod"
npm = ["jlpm"]

[tool.check-manifest]
ignore = [
  "jupytercad/labextension/**",
  "yarn.lock",
  ".*",
  "package-lock.json",
  "packages/jupytercad/src/_interface/**",
  "examples/**",
  "packages/jupytercad/*.webpack.config.js",
  "packages/jupytercad/schema.js",
]

[tool.jupyter-releaser.hooks]
before-bump-version = ["python -m pip install jupyterlab~=3.4"]
before-build-npm = ["python -m pip install 'jupyterlab>=4.0.0a25'", "jlpm"]
