[build-system]
build-backend = "hatchling.build"
requires = ["hatchling>=1.9.0", "hatch-nodejs-version", "jupyterlab>=4.0.0a25"]

[project]
name = "jupytercad"
license = { file = "LICENSE" }
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.7"
platforms = "Linux, Mac OS X, Windows"
dependencies = ["jupyter_server>=2.0.0rc3"]
classifiers = [
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Framework :: Jupyter",
    "Framework :: Jupyter :: JupyterLab",
    "Framework :: Jupyter :: JupyterLab :: 3",
    "Framework :: Jupyter :: JupyterLab :: Extensions",
    "Framework :: Jupyter :: JupyterLab :: Extensions :: Prebuilt",
]
dynamic = ["version", "description", "authors", "urls", "keywords"]

[project.optional-dependencies]
dev = [
  "hatch",
  "hatch-nodejs-version"
]

[options.entry_points.jupyter_ydoc]
jcad = "jupytercad.jcad_ydoc:YJCad"
FCStd = "jupytercad.fcstd_ydoc:YFCStd"

[tool.hatch.metadata.hooks.nodejs]
path = "packages/jupytercad/package.json"
fields = ["description", "authors", "urls", "keywords"]

[tool.hatch.build.hooks.jupyter-builder]
dependencies = ["hatch-jupyter-builder>=0.6.2"]
build-function = "hatch_jupyter_builder.npm_builder"
ensured-targets = ["jupytercad/labextension/static/style.js", "jupytercad/labextension/package.json"]
skip-if-exists = ["jupytercad/labextension/static/style.js"]

[tool.hatch.build.hooks.jupyter-builder.build-kwargs]
npm = ["jlpm"]
#source_dir = ""
#build_dir = "jupytercad/labextension"
build_cmd = "build"
editable_build_cmd = "build"


#[tool.hatch.build.hooks.jupyter-builder.editable-build-kwargs]
#npm = ["jlpm"]
#build_cmd = "build"

[tool.hatch.build]
ignore-vcs = true
only-include = ["/jupytercad", "/packages", "README.md", "package.json", "yarn.lock", "lerna.json", "install.json"]

[tool.hatch.build.targets.wheel.shared-data]
"install.json" = "share/jupyter/labextensions/jupytercad/install.json"
"jupytercad/labextension" = "share/jupyter/labextensions/jupytercad"

[tool.check-manifest]
ignore = [
  "examples/**",
  "jupytercad/labextension/**",
  "packages/jupytercad/schema.js",
  "packages/jupytercad/src/_interface/**",
  "packages/jupytercad/*.webpack.config.js",
  "yarn.lock",
  ".*",
  "package-lock.json",
]

[tool.hatch.version]
source = "nodejs"
path = "packages/jupytercad/package.json"

[tool.hatch.build.hooks.version]
path = "jupytercad/_version.py"

[tool.jupyter-releaser.options]
version_cmd = "hatch version"

[tool.jupyter-releaser.hooks]
before-bump-version = ["python -m pip install 'jupyterlab>=4.0.0a25'"]
before-build-npm = ["python -m pip install 'jupyterlab>=4.0.0a25'", "jlpm", "jlpm build"]
