[project]
name = "jupytercad-root"
readme = "README.md"
license = { file = "LICENSE" }
version = "0.3.3"

[tool.jupyter-releaser.options]
version-cmd = "python scripts/bump-version.py"
python_packages = [
    "python/jupytercad-app:jupytercad_app",
    "python/jupytercad-core:jupytercad_core",
    "python/jupytercad-lab:jupytercad_lab",
]

[tool.jupyter-releaser.hooks]
before-bump-version = ["python -m pip install hatch 'jupyterlab>=4.0.0'"]
before-build-npm = [
    "python -m pip install datamodel-code-generator jupyterlab --pre -U",
    "jlpm",
    "jlpm build:prod",
]
before-build-python = ["jlpm clean:all"]

[tool.check-wheel-contents]
ignore = ["W002"]
