name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - pydantic=2.7.4
  - ypywidgets
  - yjs-widgets
  - comm
  - pip:
      - ./jupytercad_lab-1.0.0-py3-none-any.whl
      - jupyter-shared-drive
