# a mybinder.org-ready environment for demoing jupytercad
# this environment may also be used locally on Linux/MacOS/Windows, e.g.
#
#   conda env update --file binder/environment.yml
#   conda activate jupytercad-demo
#
name: jupytercad-demo

channels:
  - conda-forge
  - conda-forge/label/jupyterlab_alpha

dependencies:
  # runtime dependencies
  - python >=3.8,<3.9.0a0
  - jupyterlab >=4.0.0a25,<5.0.0a0
  # labextension build dependencies
  - nodejs >=14,<15
  - yarn
  - pip
  - wheel
  - freecad
  # additional packages for demos
  # - ipywidgets
