# a mybinder.org-ready environment for demoing jupytercad
# this environment may also be used locally on Linux/MacOS/Windows, e.g.
#
#   conda env update --file binder/environment.yml
#   conda activate jupytercad-demo
#
name: jupytercad-demo

channels:
  - conda-forge
  - conda-forge/label/jupyterlab_alpha

dependencies:
  # runtime dependencies
  - python >=3.8,<3.9.0a0
  - jupyterlab >=4.0.0a30,<5.0.0a0
  - jupyter-server-proxy
  # extra pins for solveability
  - notebook-shim >=0.2.0
  - jupyterlab_server >=2.16.1
  # labextension build dependencies
  - nodejs >=14,<15
  - jupyter_packaging >=0.10,<2
  - yarn
  - pip
  - wheel
  # additional packages for demos
  - freecad
