name: base

channels:
  - conda-forge
  - conda-forge/label/jupyterlab_alpha

dependencies:
  # runtime dependencies
  - python >=3.8,<3.9.0a0
  - jupyterlab >=4.0.0a32,<5.0.0a0
  # extra pins for solveability
  - notebook-shim >=0.2.0
  - jupyterlab_server >=2.16.1
  # labextension build dependencies
  - nodejs >=14,<15
  - jupyter_packaging >=0.10,<2
  - yarn
  - pip
  - wheel
  # additional packages for demos
  - freecad
